services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0    
    restart: always
    ports:
      - "3307:3360"
    networks:
      - shopapp-network
    environment:
      MYSQL_ROOT_PASSWORD: Abc123456789@
      MYSQL_ROOT_HOST: "%"
  phpmyadmin8-container:
    image: phpmyadmin/phpmyadmin    
    container_name: phpmyadmin8-container
    restart: always 
    ports:
      - "8088:80" #port mapping
    environment:
      PMA_HOST: mysql8-container #phpMyAdmin Host, PMA = PHP My Amin
    networks:
      - shopapp-network
networks:
     shopapp-network:

#docker-compose -f ./deployment.yaml down
#docker container prune  xoas het cai dat
#docker-compose -f ./deployment.yaml up -d
